### ISSUE TITLE
Exclude sensitive properties while logging the request/response

### ISSUE THREAD

**Issue by yogendrasgautam** [Org-FoodService/FoodServiceAPI#25]
Currently while logging the request and response we are logging all the properties of request or response DTO.
This expose the sensitive details as well.

To achieve this, instead of using middlewares for logging request/response, Use IAsyncActionFilter.

**Comment by yogendrasgautam** [comment]
@NicolasBuscarini Found th fix for excluding sensitive information while logging, Let me know if I can start with the implementation.

**Comment by NicolasBuscarini** [comment]
Sure. Please base it on the develop branch.
